name: "build"

on:
  workflow_dispatch:
  push:
    branches:
#      - main
      - actions-failed
    paths-ignore:
      - "docs/**"
      - "**.md"
#  pull_request:
#    branches:
#      - main
#    paths-ignore:
#      - "docs/**"
#      - "**.md"

jobs:
  tcpdog:
    name: Test and build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install BCC
        run: |
          curl -sL https://github.com/mehrdadrad/tcpdog/releases/download/v1.0.0/libbcc-0.18.0-x86_64.deb --output libbcc.deb
          sudo dpkg -i libbcc.deb

      - name: Build client
        run: |
          cd tcpdog
          go build

      - name: Build server
        run: |
          cd server
          go build

      - name: Env printing
        run: |
          echo "go version: $(go version)"
          echo "sudo go version: $(sudo go version)"
          echo "\n------------ go env ------------\n"
          go env
          echo "\n------------ sudo go env ------------\n"
          sudo go env

      - name: Test
        run: sudo go test ./... -timeout 5m -coverprofile=profile.cov

      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
